# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xercise.proto\x12\x08\x65xercise\"2\n\x02ID\x12\x0b\n\x03\x64ni\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08\x66ullname\x18\x03 \x01(\t\".\n\x0bsendIDReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2;\n\x08Identify\x12/\n\x06sendID\x12\x0c.exercise.ID\x1a\x15.exercise.sendIDReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exercise_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ID']._serialized_start=28
  _globals['_ID']._serialized_end=78
  _globals['_SENDIDREPLY']._serialized_start=80
  _globals['_SENDIDREPLY']._serialized_end=126
  _globals['_IDENTIFY']._serialized_start=128
  _globals['_IDENTIFY']._serialized_end=187
# @@protoc_insertion_point(module_scope)
